### ISSUE TITLE
MediPi_Image

### ISSUE THREAD

**Issue by rprobinson** [rprobinson/MediPi#3]
![medipi_patient_unit](https://cloud.githubusercontent.com/assets/13271321/18472733/fe3ba2e8-79b0-11e6-8097-8ebc0ed732dc.jpg)

**Comment by brylie** [comment]
Where can I purchase/assemble parts to make a device like that? Can I get one pre-assembled?

**Comment by rprobinson** [comment]
This has been assembled using Over-the-counter consumer electronics from Element14: Raspberry Pi, 7" touchscreen, enclosure. I'm updating the quickstart guide and will include details

**Comment by brylie** [comment]
Thanks so much! :smile:

**Comment by rprobinson** [comment]
Readme updated :-)
